/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OutputWrap } from './outputWrap';


export interface GetOutputsResponse {
    /**
     * The list of outputs associated with this transformation, if this list is empty, the transformation doesn't have any outputs.
     */
    outputs: Array<OutputWrap>;
}
