/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LogEntry {
    /**
     * the index of the logline in the list of all loglines for this list of log entries
     */
    index: number;
    /**
     * The log level for this log entry. The value has to be one of the following: \"DEBUG\",\"INFO\",\"WARN\",\"TRACE\", \"ERROR\" or \"ALL\"
     */
    level: string;
    /**
     * The log message
     */
    message: string;
    /**
     * The unix timestamp (in milliseconds) when this log was created
     */
    timestamp: number;
}
