/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LogEntry } from './logEntry';


export interface LogResponse {
    /**
     * The End index of the logfile at the time of requesting this information.
     */
    end: number;
    /**
     * The sorted list (ascending by timestamp) of all the logs between start index and the current end index
     */
    logs: Array<LogEntry>;
    /**
     * The requested start index
     */
    start: number;
}
