/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlatformResponse {
    /**
     * The identifier for this platform (plugin)
     */
    id: string;
    /**
     * The name for this platform (plugin)
     */
    name: string;
}
