/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PropertyWrap {
    /**
     * The description that should be displayed on the Frontend to describe the key
     */
    description: string;
    /**
     * the unique key for a property
     */
    key: string;
    /**
     * Determines if the property is required to start the transformation
     */
    required: boolean;
    /**
     * The \"Datatype\" of a property. Supported Types are \"name\", \"text\", \"boolean\", \"integer\", \"unsigned_integer\", \"float\" and \"secret\"
     */
    type: string;
    /**
     * gcr.io
     */
    value?: string;
}
