/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CsarResponse } from './csarResponse';
import { Link } from './link';


export interface ResourcesCsarResponse {
    _embedded?: Array<CsarResponse>;
    links?: Array<Link>;
}
