/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Link } from './link';
import { TransformationResponse } from './transformationResponse';


export interface ResourcesTransformationResponse {
    _embedded?: Array<TransformationResponse>;
    links?: Array<Link>;
}
