/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ValidationPropertyWrap } from './validationPropertyWrap';


export interface SetPropertiesResponse {
    /**
     * This value is true if the internal validation of the property was succesful, False otherwise
     */
    properties: Array<ValidationPropertyWrap>;
}
