/**
 * TOSCAna
 * To be Done!
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SetPropertiesResponse {
    /**
     * Key - Boolean map, telling you which values have been set properly (true) and which ones have failed (false).
     */
    validInputs: { [key: string]: boolean; };
}
