package org.opentosca.toscana.model.datatype;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import lombok.Data;

/**
 Describes logical network information.
 <p>
 (TOSCA Simple Profile in YAML Version 1.1, p. 143)
 */
@Data
public class NetworkInfo {

    // TODO this class needs to get reworked completely (use ToscaKeys instead of normal fields - just like in the Credential class)

    /**
     The name of the logical network.
     <p>
     e.g., “public”, “private”, “admin”. etc.
     <p>
     (TOSCA Simple Profile in YAML Version 1.1, p. 143)
     */
    private final String networkName;

    /**
     The unique ID of for the network generated by the network provider.
     <p>
     (TOSCA Simple Profile in YAML Version 1.1, p. 143)
     */
    private final String networkId;

    /**
     The list of IP addresses assigned from the underlying network.
     <p>
     (TOSCA Simple Profile in YAML Version 1.1, p. 143)
     */
    private final Set<String> addresses = new HashSet<>();

    public NetworkInfo(String networkName, String networkId) {
        this.networkName = Objects.requireNonNull(networkName);
        this.networkId = Objects.requireNonNull(networkId);
    }
}
    
