###############################
##### TOSCAna Properties ######
###############################
server:
    port: 8084
toscana:
    docker:
        base-image-mapper:
            # This defines the Update interval of the Base Image Mapper.
            # it will update the Base images every x Hours
            update-interval: 24


################################
##### Spring HTTP Settings #####
################################

spring:
    resources:
        chain:
            enabled: true
    main:
        banner-mode: "off"
    http:
        multipart:
            enabled: true
            max-file-size: 10000MB
            max-request-size: 10000MB
            file-size-threshold: 10MB

######################################
##### Data Directory Properties ######
######################################

# no fallback value supplied here. value is computed at runtime, as it is platform dependent
# use this at runtime
datadir: 
# if datadir was not supplied, datadir falls back to these values (depending on runtime environment)
datadir_win: ${user.home}/AppData/toscana
datadir_nix: ${user.home}/.toscana

##########################################
##### SPRING BOOT ACTUATOR SETTINGS ######
##########################################

# Disable security for spring boot actuator
management:
    security:
        enabled: false

# Comment out the following part to get full access to all spring boot actuator features
endpoints:
    enabled: false
    metrics:
        enabled: true
        path: /api/status/metrics
    health:
        enabled: true
        path: /api/status/health
    # TODO Only keep mappings enabled during development
    mappings:
        enabled: true
        path: /api/status/mappings
