spring:
  main:
    banner-mode: "off"
#  http:
#  	multipart:
#     enabled: true
#     max-file-size: 10000MB
#     max-request-size: 100000MB
     
    

# no fallback value supplied here. value is computed at runtime, as it is platform dependent
# use this at runtime
datadir: 
# if datadir was not supplied, datadir falls back to these values (depending on runtime environment)
datadir_win: ${user.home}/AppData/toscana
datadir_nix: ${user.home}/.toscana

