---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "test-app"
  name: "test-app-service"
  ownerReferences: []
spec:
  deprecatedPublicIPs: []
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 80
  selector:
    app: "test-app"
  type: "NodePort"
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations: {}
  finalizers: []
  labels: {}
  name: "test-app-deployment"
  ownerReferences: []
spec:
  replicas: 1
  selector:
      app: "test-app"
  template:
    metadata:
      name: "test-app"
      annotations: {}
      finalizers: []
      labels:
        app: "test-app"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: []
        image: "nfode/simpletaskapp:v1"
        name: "test-app"
        ports:
        - containerPort: 80
        volumeMounts: []
      imagePullSecrets: []
      nodeSelector: {}
      volumes: []
